### ISSUE TITLE
Release Zeebe Modeler v0.9.0

### ISSUE THREAD

**Issue by nikku** [zeebe-io/zeebe-modeler#183]
__What is inside__

* [x] Update to latest Camunda Modeler foundation (https://github.com/zeebe-io/zeebe-modeler/issues/187)
* [x] Error end event support (https://github.com/zeebe-io/zeebe-modeler/issues/162)
* [x] Deploy / Run from Modeler (https://github.com/zeebe-io/zeebe-modeler/issues/53, https://github.com/zeebe-io/zeebe-modeler/issues/177)
* [x] Improved Deploy dialog (https://github.com/zeebe-io/zeebe-modeler/issues/186)
* [x] Various UI fixes / alignments
* [x] Branding update (Watermark, Loading indicator)

__Checklist__

* [x] put up code freeze appointment in calendar (include `modeling`, `qa`, `sre`, `zeebe` and `Team-Support`)
* [x] make sure dependencies are released (`rm -rf node_modules && npm i && npm run all` works)
    * `bpmn-js`, `*-properties-panel`, `*-moddle`, ...
* [x] close all issues which are solved by dependency updates
* [x] verify `develop` is up to date with `master`: `git checkout master && git pull && git checkout develop && git merge master`
* [x] smoke test to verify all diagrams can be created
* [x] update CHANGELOG
* [x] semantic release (`npm run release`)
* [x] merge to master: `git checkout master && git merge develop`
* [x] wait for CI infrastructure to build the release, cf. [release build](https://travis-ci.com/github/zeebe-io/zeebe-modeler/builds/160498966)
* [x] execute [integration test](https://github.com/zeebe-io/zeebe-modeler/blob/master/docs/.project/INTEGRATION_TEST.md) on [released artifacts](https://github.com/zeebe-io/zeebe-modeler/releases/tag/untagged-d60c0bdf413184cd0e0e)
    * [x] Works on Linux @mschoe 
    * [x] Works on Mac @pinussilvestrus 
    * [x] Works on Windows @philippfromme 
* [x] trigger QA for fuzzy testing
* [x] Publish release on [Github Releases](https://github.com/zeebe-io/zeebe-modeler/releases)
* [x] <del>write blog post on _?_</del>
* [x] spread the word
    * [x] send [release notice email](https://github.com/bpmn-io/internal-docs/blob/master/camunda-modeler/README.md#release-notice-email)
    * [x] <del>tweet</del>
* [x] Close [current milestone](https://github.com/zeebe-io/zeebe-modeler/milestones), if it exists
