### ISSUE TITLE
Improve deployment tool

### ISSUE THREAD

**Issue by barmac** [zeebe-io/zeebe-modeler#200]
* [x] Implement new designs https://github.com/zeebe-io/zeebe-modeler/issues/186
* [x] Save file before deployment tool is displayed https://github.com/zeebe-io/zeebe-modeler/issues/199
* [x] Implement new input validation logic (cf. https://github.com/zeebe-io/zeebe-modeler/pull/194#issuecomment-609604117)
* [x] Differentiate between authentication method and deployment target https://github.com/zeebe-io/zeebe-modeler/issues/203
* [ ] ~~Save only relevant endpoint configuration https://github.com/zeebe-io/zeebe-modeler/issues/201~~

**Comment by pinussilvestrus** [comment]
>  Implement new input validation logic (cf. #194 (comment))

@barmac do we know whether and what improvements to be made?

**Comment by barmac** [comment]
> > Implement new input validation logic (cf. #194 (comment))
> 
> @barmac do we know whether and what improvements to be made?

For now, this will be only https://github.com/zeebe-io/zeebe-modeler/issues/203 (I will update this in a few minutes).
