### ISSUE TITLE
Release Zeebe Modeler v0.10.0

### ISSUE THREAD

**Issue by nikku** [zeebe-io/zeebe-modeler#232]
## What is inside

* [x] New app icon (https://github.com/zeebe-io/zeebe-modeler/issues/220)
* [x] Pull in latest Camunda Modeler Changes (`npm run sync -- -t 4.2.0`) (https://github.com/zeebe-io/zeebe-modeler/issues/241)
* [x] Spaces allowed in properties (https://github.com/zeebe-io/zeebe-modeler/issues/231, https://github.com/zeebe-io/zeebe-modeler/issues/223)
* [x] Potentially smaller GRPC client (https://github.com/zeebe-io/zeebe-modeler/issues/230)
* [x] Disallow typed start events in sub-processes (#69)
* [x] Output mappings for all event types (#242)

## Release Checklist
_To be done immediately after creating this issue._

* [x] put up code freeze appointment in calendar (include `modeling`, `qa`, `infra`, `zeebe` and `Team-Support`)
* [x] put up release appointment in calendar (include `modeling` and Marketing [Charley Mann & Christopher Rogers])

_To be done after code freeze and prior to the release day to prepare and build the release._

* [x] make sure dependencies are released (`rm -rf node_modules && npm i && npm run all` works)
    * `bpmn-js`, `dmn-js`, `cmmn-js`, `*-properties-panel`, `*-moddle`, ...
* [x] close all issues which are solved by dependency updates
* [x] verify `develop` is up to date with `master`: `git checkout master && git pull && git checkout develop && git merge master`
* [x] smoke test to verify all diagrams can be created
* [x] update CHANGELOG
* [x] merge to master: `git checkout master && git merge develop`
* [x] create release candidate (`npm run release`), e.g. v1.0.0-rc.0
    * [x] wait for [Travis](https://travis-ci.com/zeebe-io/zeebe-modeler) to build the executables
* [x] execute [integration test](https://github.com/zeebe-io/zeebe-modeler/blob/master/docs/.project/INTEGRATION_TEST.md) on [released artifacts](https://github.com/zeebe-io/zeebe-modeler/releases)
    * [x] Works on Linux
    * [x] Works on Mac
    * [x] Works on Windows
* [x] trigger QA for fuzzy testing

_To be done after integration test was successful or if not issues were fixed._

* [x] create release (`npm run release`), cf. [release schema](https://github.com/bpmn-io/internal-docs/tree/master/release-schema)
    * [x] wait for [Travis](https://travis-ci.com/zeebe-io/zeeber-modeler) to build the executables

_To be done on release day to announce the release and making it publically available._

* [x] publish release on [Github Releases](https://github.com/zeebe-io/zeebe-modeler/releases)
* [x] write blog post on [Zeebe Blog](https://github.com/zeebe-io/zeebe.io/tree/master/content/blog), if applicable
* [x] spread the word
    * [x] send [release notice email](https://github.com/bpmn-io/internal-docs/blob/master/zeebe-modeler/README.md#release-notice-email)
    * [ ] tweet
* [x] close [current milestone](https://github.com/zeebe-io/zeebe-modeler/milestones)
