### ISSUE TITLE
New Zeebe attribute "propagateAllChildVariables" for call activities 

### ISSUE THREAD

**Issue by saig0** [zeebe-io/zeebe-modeler#252]
__Is your feature request related to a problem? Please describe.__

Zeebe supports a new (boolean) attribute "propagateAllChildVariables" for call activities. It can be set to `true` or `false`.

If it is set to `true` then all variables are propagated (i.e. copied) from the child instance to the parent instance. Otherwise, no variables are copied. 

If an output mapping is defined on the call activity then the output mapping is applied and only the defined variables are propagated.

The Zeebe modeler should support the new attribute.

The related issue in Zeebe: https://github.com/zeebe-io/zeebe/issues/4860#issuecomment-682519598

__Describe the solution you'd like__

In the Zeebe modeler, I can set the attribute "propagateAllChildVariables" for call activities. For example, by enabling or disabling a flag on the details section of the activity next to the process id. 

By default, the attribute should be set to `false`. This avoids that variables are overridden accidentally in a parallel flow (e.g. multi-instance parallel call activity). If the attribute is not present then Zeebe interprets it as `true` to be backward-compatible. So, new BPMN workflows should serialize the attribute. But existing workflows should not serialize the attribute (or with value `true`) if the attribute is not changed/disabled to avoid changing in the behavior of the workflow.  

The user should be notified (e.g. a warning or failure message) if the attribute is set to `true` and output mappings are defined. If output mappings are defined then it propagates only the variables that are defined in the mapping.

__Decided design and tasks as of kickoff 20th October 2020__ 

Also see https://github.com/zeebe-io/zeebe-modeler/issues/252#issuecomment-712833797

- [x] Pull in latest bpmn-js-prop-panel version (so to have new I/O GUI components available) (see https://github.com/zeebe-io/zeebe-modeler/issues/261)
- [x] Update zeebe moddle (see https://github.com/zeebe-io/zeebe-bpmn-moddle/pull/2)
- [x] Migrate existing I/O tabs to use new / improved I/O GUI component and improve labels (https://github.com/zeebe-io/zeebe-modeler/issues/265)
- [x] Implement toggle switch for propageteAllChildVariables setting `propagateAllChildVariables` and disabling/deleting output parameter mappings (#267)
- [x] Implement migration behavior for callActivites without `propagateAllChildVariables` (issue tbd)

__Describe alternatives you've considered__

No.

__Additional context__

BPMN XML of a call activity: 
```
  <bpmn:callActivity id="Activity_1h7j9o6" name="A">
      <bpmn:extensionElements>
        <zeebe:calledElement processId="demo-process" propagateAllChildVariables="false" />
      </bpmn:extensionElements>
      <bpmn:incoming>Flow_1t0ia8l</bpmn:incoming>
      <bpmn:outgoing>Flow_0ypungt</bpmn:outgoing>
    </bpmn:callActivity>
```

**Comment by MaxTru** [comment]
Depends on https://github.com/zeebe-io/zeebe-bpmn-moddle/issues/1

**Comment by MaxTru** [comment]
> The user should be notified (e.g. a warning or failure message) if the attribute is set to true and output mappings are defined. 

Is a validation of the respective checkbox what you expect / sufficient?

**Comment by saig0** [comment]
@MaxTru a validation would be an option :heavy_check_mark:  
It is to avoid a misconfiguration. You can deploy such a workflow to Zeebe but it might not work as the user expect.

**Comment by MaxTru** [comment]
Affected/blocked by: https://github.com/bpmn-io/bpmn-js-properties-panel/issues/359

**Comment by MaxTru** [comment]
Assigning it to @volkergersabeck to do PM evaluation of this issue before implementation.

**Comment by saig0** [comment]
@volkergersabeck when do you plan to implement this feature? 

This issue would solve a major issue in Zeebe. It is easy for users to run into this bug because the current (default) behavior is not intuitive.

**Comment by MaxTru** [comment]
@saig0 I scheduled a quick sync to clarify some conceptual questions (see your calendar), afterwards we can implement this rather quickly IMO. Hope this helps, please feel free to reach out in case of questions.

**Comment by MaxTru** [comment]
**Kickoff performed on 20.October together with @saig0, @andreasgeier, @volkergersabeck  and myself.

Key decisions:

* First we will change the I/O mapping component to the more recent version, that we also use in the Modeler (https://github.com/bpmn-io/bpmn-js-properties-panel/issues/350)
* For the CallActivity I/O tab, a toggle/slider `Propagate all child variables?` will be added on top of the output parameter mapping. This toggle will control whether it is possible to have output parameter mappings or not.
  * Toggle on equals to `true`, and off equals to `false`
  * If the toggle is `on`, it is not possible to add output parameter mappings. 
  * If the toggle is set to `on`, existing output parameter mappings will be deleted.
  * If the toggle is `off`, the output parameter mapping component will work as usual.
* [For new CallActivities created]: the toggle is `off` as default.
* [Migration]: existing diagrams (without the `propagateAllChildVariables` will be migrated). This means:
  * An old callActivity without the property and without output parameter mappings => set the property to `true` (and toggle `on`)
  * An old callActivity without the property but with existing output parameter mappings => set the property to `false` (and toggle `false`)

**Comment by pinussilvestrus** [comment]
Closed via https://github.com/zeebe-io/zeebe-modeler/pull/271
