### ISSUE TITLE
Release Zeebe Modeler v0.11.0

### ISSUE THREAD

**Issue by MaxTru** [zeebe-io/zeebe-modeler#277]
## What's inside?

* Improved Input Output Tab (https://github.com/zeebe-io/zeebe-modeler/issues/265)
* Support propagateAllChildVariables on callActivities (https://github.com/zeebe-io/zeebe-modeler/issues/267)
* Support canCopyProperty logic (https://github.com/zeebe-io/zeebe-modeler/issues/248)

## Release Checklist

Note: The release manager in charge will be determined by the Camunda Modeler Release Manager (cf. [Camunda Modeler Release Checklist](https://github.com/camunda/camunda-modeler/blob/master/docs/.project/RELEASE.md))

_To be done immediately after creating this issue._

* [x] put up code freeze appointment in calendar (include `modeling`, `qa`, `infra`, `zeebe` and `Team-Support`)
* [x] put up release appointment in calendar (include `modeling`, `DevRel` and Marketing [Charley Mann & Christopher Rogers])

_To be done after code freeze and prior to the release day to prepare and build the release._

* [x] make sure changes in upstream libraries are merged and released
    * `bpmn-js`, `*-properties-panel`, `*-moddle`, ...
    * [x] Release `bpmn-js@7.5.0`, https://github.com/bpmn-io/bpmn-js/issues/1377
    * [x] Release `bpmn-js-properties-panel@0.37.6`
* [x] make sure dependencies to upstream libraries are updated and can be installed (`rm -rf node_modules && npm i && npm run all` works)
* [x] close all issues which are solved by dependency updates
* [x] verify `develop` is up to date with `master`: `git checkout master && git pull && git checkout develop && git merge master`
* [x] smoke test to verify all diagrams can be created
* [x] update CHANGELOG
* [x] merge to master: `git checkout master && git merge develop`
* [x] create release candidate (`npm run release`), e.g. v0.11.0-rc.0
    * [x] wait for [Travis](https://travis-ci.com/zeebe-io/zeebe-modeler) to build the executables
* [x] execute [integration test](https://github.com/zeebe-io/zeebe-modeler/blob/master/docs/.project/INTEGRATION_TEST.md) on [released artifacts](https://github.com/zeebe-io/zeebe-modeler/releases)
    * [x] Works on Linux
    * [x] Works on Mac
    * [x] Works on Windows
* [x] trigger QA for fuzzy testing
* [x] (Since we are DRI for release notice mail): initiate release mail process (see https://github.com/zeebe-io/zeebe-modeler/issues/277#issuecomment-738698587)

_To be done after integration test was successful or if not issues were fixed._

* [x] create release (`npm run release`), cf. [release schema](https://github.com/bpmn-io/internal-docs/tree/master/release-schema)
    * [x] wait for [Travis](https://travis-ci.com/zeebe-io/zeeber-modeler) to build the executables

_To be done on release day to announce the release and making it publically available._

* [x] publish release on [Github Releases](https://github.com/zeebe-io/zeebe-modeler/releases)
* [ ] ~write blog post on [Zeebe Blog](https://github.com/zeebe-io/zeebe.io/tree/master/content/blog), if applicable~
* [x] spread the word
    * [x] send [release notice email](https://github.com/zeebe-io/zeebe-modeler/issues/277#issuecomment-738698587) (but exclude Zeebe Modeler)
    * [ ] ~tweet~
* [ ] close [current milestone](https://github.com/zeebe-io/zeebe-modeler/milestones)

**Comment by MaxTru** [comment]
**Relase Notice Mail Update**

* We will not send a release notice mail for Zeebe Modeler, since that would trigger a support notification.
* Since we are - for this stack release (see [here](https://confluence.camunda.com/display/camBPM/Release+Presentation+Organization)) - the DRI for organizing the release presentation, we (ie. @azeghers are also responsible for the relase notice mail). This means we need to do:

- [ ] **On Friday:**
  - [ ] Create a copy of the [template](https://docs.google.com/document/d/1-qWU8EnfahryeUBPLQexgKO6mzYH5eqMYLrFDqNFYRY/edit) inside the Google Drive folder [Release Notifications](https://drive.google.com/drive/folders/1hziaQOP3vzshJicigEY5ME4BFj--ObYV?usp=sharing)
  - [ ] Adjust the release versions by applying the information provided in [Confluence - Release Dates](https://confluence.camunda.com/display/camBPM/Release+Dates)
  - [ ] Share the document with the release managers
(All release managers are requested to share information about their release:
Blog post links as soon as they are available
Release notes aka Change Log (if applicable)
The deadline to share the information is the second Monday of a month EOB, i.e., one day before launching the release.)

- [ ] **On Release Day (Tuesday):**
  - [ ] Add the recording link to the document
  - [ ] Make sure that all links are working properly - if this is not the case, the DRI checks in with the respective release manager
  - [ ] Open a new email in Outlook and copy & paste the content from the document into it
  - [ ] Ensure that the formatting looks fine in the email
  - [ ] Set email subject: Camunda Releases - LIST_OF_RELEASED_PRODUCTS
  - [ ] Replace all placeholders like LIST_OF_RELEASED_PRODUCTS, YOUR_NAME, etc.
  - [ ] Send the mail to TO: roman.smirnov@camunda.com, richard.weinberg@camunda.com and BCC: alle@camunda.com
