### ISSUE TITLE
Update to Camunda Modeler @next infrastructure

### ISSUE THREAD

**Issue by nikku** [zeebe-io/zeebe-modeler#32]
> This issue tracks the progress of updating the Zeebe Modeler to the upcoming [Camunda Modeler @next foundations](https://github.com/camunda/camunda-modeler/issues/866).

__Context__

Hi @dominikhrn. First of all, thank you for maintaining the Zeebe Modeler :clap:.

In the Camunda Modeling sphere we are working hard on the next version of our modeler foundation. You may follow the progress [here](https://github.com/camunda/camunda-modeler/issues/866). The new foundation applies numerous under-the-hood improvements, including:

* improved client app maintainability and extensibility by making it a react application
* improved client/backend communication and separation of responsibilities
* efficiently build the client application, resulting in better responsiveness of the application
* improved testing and code coverage
* improved release builds

The overall goal we aim to achieve is simpler maintenance and readiness for future extensions.

__Road Forward__

We plan to contribute the infrastructure improvements implemented in Camunda Modeler @next to this project once we reached our `3.0.0-0` target. 

__Tasks__

* [x] Update to Camunda Modeler @next
* [x] Add automated release and nightly builds (https://github.com/zeebe-io/zeebe-modeler/issues/6)
* [x] Add / Improve test infrastructure (https://github.com/zeebe-io/zeebe-modeler/issues/4)
* [x] Improve user documentation (focus on `README` for now, https://github.com/zeebe-io/zeebe-modeler/issues/35)
* [x] Setup and document a way to keep up-to-date with upstream Camunda Modeler

Stay tuned for pull requests that contribute the changes :rocket:.

**Comment by nikku** [comment]
From my point of view this issue can be closed. :car:

**Comment by menski** [comment]
Big thanks to everyone involved that was impressive progress :clap:
